issue 8: moderation
rfc-editor/draft-eggert-bcp45bis pull request #11
Opened 2022-05-04 20:07 UTC by sginoza

closes #8

2022-05-12 20:58 UTC, sginoza commented
@larseggert is this change acceptable?

2022-05-13 05:55 UTC, larseggert requested changes

2022-05-13 05:55 UTC, larseggert commented on draft-eggert-bcp45bis.md
> +lists. Moderators are selected by the community to moderate the community list. Because the IESG and IAB are in the appeals
This is not accurate. Moderators are selected by the IETF Chair.

2022-05-18 16:40 UTC, sginoza commented
resolved by #14

2022-05-18 16:40 UTC, closed without merging